# Generated by Django 4.0.6 on 2022-07-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0002_remove_events_user_events_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='user_name',
            new_name='user_profile',
        ),
    ]
