# Generated by Django 4.0.6 on 2022-07-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0003_rename_user_name_events_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='user_profile',
            new_name='reguser',
        ),
    ]
