# Generated by Django 4.0.6 on 2022-07-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0004_rename_user_profile_events_reguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='id',
        ),
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
