# Generated by Django 4.0.6 on 2022-07-22 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event_registration', '0007_rename_event_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='reguser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
