# Generated by Django 4.0.6 on 2022-07-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0009_alter_userevent_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='image',
            field=models.TextField(max_length=100),
        ),
    ]
